# Generated by Django 5.1.7 on 2025-03-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0003_booking"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
