# Generated by Django 5.1.7 on 2025-03-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0004_delete_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatrimonyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("district", models.CharField(max_length=100)),
                ("gothram", models.CharField(max_length=100)),
                ("star", models.CharField(max_length=100)),
                ("education", models.CharField(max_length=255)),
                ("job", models.CharField(max_length=255)),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("partner_expectations", models.TextField(blank=True, null=True)),
                ("contact_number", models.CharField(max_length=15)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="matrimony_profiles/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Temple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("district", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("google_maps_link", models.URLField(blank=True, null=True)),
                ("history", models.TextField(blank=True, null=True)),
                ("pooja_timings", models.TextField()),
                ("facilities", models.TextField(blank=True, null=True)),
                ("contact_number", models.CharField(max_length=15)),
                (
                    "main_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="temple_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="WeddingHall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("district", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("capacity", models.IntegerField()),
                ("facilities", models.TextField()),
                ("rental_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("contact_number", models.CharField(max_length=15)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "images",
                    models.ImageField(
                        blank=True, null=True, upload_to="wedding_halls/"
                    ),
                ),
            ],
        ),
    ]
